<?xml version="1.0" encoding="utf-8"?><Database Name="Enseignement.mdf" Class="DataClassesEnseignementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-Q80DI9U\SQLEXPRESS;Initial Catalog=Enseignement.mdf;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Enseignement_mdfConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Eleves" Member="Eleves">
    <Type Name="Eleves">
      <Column Name="ID_Eleve" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CNE" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Tel" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>